### ISSUE TITLE
Admin Dashboard Improvements

### ISSUE THREAD

**Issue by abrahamcacoulides** [EaryOrtiz/ProodFloorCSharpp#62]
Add search/filter feature to:

- Door Operators
-Fire Codes
-Landing Systems
- Countris
- States
- Cities
- Engineer References
- Users
- Roles

Basically every data base being handled through the application should include the search/filter option.

**Comment by EaryOrtiz** [comment]
We added search/ filter for the features that has more than 10 items on the DB
These objects does not have filter/search
- Country
- JobTypes
